module FiveDay exposing (..)

import CssStyles exposing (..)
import Html exposing (..)
import Html.Attributes exposing (..)


view =
    div [ class "fiveday-container col-6", style halfBox ]
        [ ul [ style unordered ]
            [ li [ class "5", style listItem ]
                [ span [ class "five-day", style fiveDay ]
                    [ text "Fri" ]
                , div [ class "five-temps", style fiveRange ]
                    [ p [ class "five-hi", style fiveTemps ]
                        [ text "hi: 80°" ]
                    , p [ class "five-lo", style fiveTemps ]
                        [ text "lo: 60°" ]
                    ]
                ]
            , li [ class "5", style listItem ]
                [ span [ class "five-day", style fiveDay ]
                    [ text "Fri" ]
                , div [ class "five-temps", style fiveRange ]
                    [ p [ class "five-hi", style fiveTemps ]
                        [ text "hi: 80°" ]
                    , p [ class "five-lo", style fiveTemps ]
                        [ text "lo: 60°" ]
                    ]
                ]
            , li [ class "5", style listItem ]
                [ span [ class "five-day", style fiveDay ]
                    [ text "Fri" ]
                , div [ class "five-temps", style fiveRange ]
                    [ p [ class "five-hi", style fiveTemps ]
                        [ text "hi: 80°" ]
                    , p [ class "five-lo", style fiveTemps ]
                        [ text "lo: 60°" ]
                    ]
                ]
            , li [ class "5", style listItem ]
                [ span [ class "five-day", style fiveDay ]
                    [ text "Fri" ]
                , div [ class "five-temps", style fiveRange ]
                    [ p [ class "five-hi", style fiveTemps ]
                        [ text "hi: 80°" ]
                    , p [ class "five-lo", style fiveTemps ]
                        [ text "lo: 60°" ]
                    ]
                ]
            , li [ class "5", style listItem ]
                [ span [ class "five-day", style fiveDay ]
                    [ text "Fri" ]
                , div [ class "five-temps", style fiveRange ]
                    [ p [ class "five-hi", style fiveTemps ]
                        [ text "hi: 80°" ]
                    , p [ class "five-lo", style fiveTemps ]
                        [ text "lo: 60°" ]
                    ]
                ]
            , li [ class "5", style listItem ]
                [ span [ class "five-day", style fiveDay ]
                    [ text "Fri" ]
                , div [ class "five-temps", style fiveRange ]
                    [ p [ class "five-hi", style fiveTemps ]
                        [ text "hi: 80°" ]
                    , p [ class "five-lo", style fiveTemps ]
                        [ text "lo: 60°" ]
                    ]
                ]
            ]
        ]
